### ISSUE TITLE
Support attribute and relationship with same name?

### ISSUE THREAD

**Issue by pmurph0** [kamikat/moshi-jsonapi#115]
This is a valid JSON API spec payload, with an attribute and relationship both called `payments`

> {
      "id": "ID_HERE",
      "type": "checks",
      "attributes": {
        "payments": [
          {
            "id": "ID_HERE",
            "check_id": "ID_HERE",
          }
        ]
      },
      "relationships": {
        "payments": {
          "data": [
            {
              "type": "payments",
              "id": "ID_HERE"
            }
          ]
}

But I can't deserialize it to my model which looks like this:

> @JsonApi(type = "checks")
data class Check(
@Json(name = "payments") val paymentsResource: HasMany<PaymentResource>? = null,
@Json(name = "payments") val payments: List<Payment>? = emptyList()
)

As the deserializer complains of a clash when mapping because of having 2 fields with the same Json name:

> com.squareup.moshi.JsonDataException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.data[0].relationships.payments

Is there a way to handle this?

**Comment by kamikat** [comment]
I'm sorry but actually that's not a valid JSONAPI resource according to the [spec](https://jsonapi.org/format/#document-resource-object-fields):

> a resource can not have an attribute and relationship with the same name

Maybe we can have some test case for this :smile:
