### ISSUE TITLE
Add 'supported features' section in README

### ISSUE THREAD

**Issue by mreichelt** [kamikat/moshi-jsonapi#17]
To keep track of what is supported and what isn't we should add a 'supported features' section in the README, containing something similar to this Swift JSONAPI library:
https://github.com/wvteijlingen/Spine#supported-features

**Comment by kamikat** [comment]
Sweet idea! But in contrast to Spine, moshi-jsonapi simply serialize/deserialize JSON API document. Support to meta object and resource link is still under development and they can be checked from a Todo section. So I think it's not that necessary for now. Thanks anyway.

**Comment by mreichelt** [comment]
That's why I said 'similar' - I know Spine has a broader use case.
A 'supported features' table is always nice, because it not only shows the features not yet implemented, but what's actually implemented (and therefore usable).
I'll make a PR to show what I mean. :)

**Comment by mreichelt** [comment]
@kamikat if you change your mind, I have a PR ready to go. :)
You can preview it here:
https://github.com/mreichelt/moshi-jsonapi/tree/fix-17-add-supported-features-to-readme#supported-features
