### ISSUE TITLE
Remove ResourceNotFoundException

### ISSUE THREAD

**Issue by mreichelt** [kamikat/moshi-jsonapi#24]
Instead of using `ResourceNotFoundException` I suggest we should simply return `null` instead.
Reasons:

- The check against null is pretty common for developers.
- IDEs have built-in support for methods returning null.
- Null is a common use case for jsonapi – common use cases should not throw exceptions.
- This would also solve #12 in a jiffy – finding this info is a null check. :)

**Comment by kamikat** [comment]
When a `ResourceNotFoundException` thrown from `get()` it means that the referenced resource is not provided by `Document` or there is not document related with current `Resource` object. When there is a `null` value of a relationship the value of `HasOne<>`/`HasMany<>` should be `null`, and there's no matter with `ResourceNotFoundException`.

**Comment by kamikat** [comment]
**UPDATE** I've update the document. We're now returning `null` when `HasOne/HasMany` cannot found resources. `ResourceNotFoundException` is reserved for `Document.find(String, String)`

**Comment by mreichelt** [comment]
@kamikat Thanks!
`Document.find(String, String)` is a good example for my case: It should behave nearly like a Map in Java – which returns null if a value can not be found.

**Comment by mreichelt** [comment]
@kamikat I added a PR for simply merge-and-be-happy if you like the change. :)
https://github.com/kamikat/moshi-jsonapi/pull/25
