### ISSUE TITLE
Serialize with Relationship

### ISSUE THREAD

**Issue by mirmousaviii** [kamikat/moshi-jsonapi#32]
I use Relationship in Serialize.
Article Model:
```
@JsonApi(type = "articles")
public class Article extends Resource {
    public String title;
    public HasOne<Person> author;
}
```
Person Model:
```
@JsonApi(type = "people")
public class Person extends Resource {
    public String name;
}
```
Use Serialize:
```
Person people = new Person();
people.setId("2");
people.name = "Test2222";

Article article = new Article();
article.title = "Test111";
article.author = HasOne.create(article, people);

Document.of(article);

moshi.adapter(Article.class).toJson(article);
```
But my result is:
```
{"data":{"type":"articles","attributes":{"title":"Test111"},"relationships":{"people":{"data": "type": "people", id: "2"}}}}
```
people.name is not set!

**Comment by kamikat** [comment]
Seems that it works well according to JSON API 1.0. `relationships > people` is a **Resource Linkage** not a **Resource**. BTW, JSON API 1.0 does not support the behavior to create a batch of resource with relationships between them. 

And a workaround is to use `moshi.adapter(Resource[].class).toJson(new Resource[] { article, people });` and have server support a client generated id. The idea is, add all resources needs to be created to document and use a client generated id to connect each other.
