### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by deshmukhrohit11** [kamikat/moshi-jsonapi#35]
I am newbie to moshi-jsonapi.

I am using JSONAPI in my project. I have one attribute of Date. I am getting error for it.
                                                                                     
**java.lang.IllegalArgumentException: Platform class java.util.Date annotated [] requires explicit JsonAdapter to be registered**

Any one have any idea?

**Comment by kamikat** [comment]
An extra `Date` adapter should be add to moshi instance for things to work.

If you're using RFC3339, add `com.squareup.moshi:moshi-adapters` to project dependencies and use `Rfc3339DateJsonAdapter`:

```java
Moshi moshi = new Moshi.Builder()
    ...
    .add(Date.class, new Rfc3339DateJsonAdapter())
    .build();
```

Otherwise, create custom `JsonAdapter` and add that to moshi likewise.

**Comment by deshmukhrohit11** [comment]
Thank you. It work like charm..
