### ISSUE TITLE
Is there any annotation for id like type?

### ISSUE THREAD

**Issue by deshmukhrohit11** [kamikat/moshi-jsonapi#38]
I need to map Contacts id to one of the attribute. Do we have any annotation for it?

I need to map id to another attribute in Contacts class. Like contactId map to id("id": "5210")
{
  "data": [
    {
      "type": "contacts",
      "id": "5210",
      "attributes": {}
   }
 ]
}

Class:
@JsonApi(type = "contacts")
public class Contact extends Resource {
	
	private int contactId; // I want to map it to  "id": "5210"
}

**Comment by deshmukhrohit11** [comment]
Any one how to do this? I am blocked because of this issue.

**Comment by kamikat** [comment]
I'm afraid it's impossible to do this mapping. And the `id` of a resource can only be accessed using `Contact.getId()`.
