### ISSUE TITLE
Ambiguous documentation

### ISSUE THREAD

**Issue by lordplagus02** [kamikat/moshi-jsonapi#4]
This code doesn't compile:

```
String json = "...";

Moshi.Builder builder = new Moshi.Builder();
builder.add(ResourceAdapterFactory.builder()
        .add(Article.class)
        .add(Person.class)
        .add(Comment.class)
        .build());

Article[] articles = moshi.adapter(Articles[].class).fromJson(json);
```

The readme needs a proper explanation of how to set up the adapter for version 2.x because due to all the breaking changes, it no longer makes sense.

**Comment by kamikat** [comment]
Thanks. I've updated the documentation. Is it clear enough now?
