### ISSUE TITLE
Why are Resource .equals and .hashCode final?

### ISSUE THREAD

**Issue by tmtrademarked** [kamikat/moshi-jsonapi#48]
This was a change introduced between 2.2.0 and 3.0.6, and it's a breaking change for clients. It also seems to serve no real purpose - if users wish to override equals/hashcode, what would it break?

At the very least, some comments in the source explaining why these are final would be appreciated.

**Comment by kamikat** [comment]
I have to admit that it's an unexpected coupling to make it easier to implement relationship lookup which should be change in the future. BTW, `.equals` and `.hashCode` are declared final in `ResourceIdentifier`. Changing the inheritance relationship between `ResourceIdentifier` and `Resource` should also be taken into consideration.
