### ISSUE TITLE
Attributes title not string

### ISSUE THREAD

**Issue by antonicg** [kamikat/moshi-jsonapi#52]
Is there any trouble if the attributes object inside a Resource has a title that is an object instead of String? I have this case, also I'm trying to use my own attributes object with no success. Is a limitation of the library?

**Comment by kamikat** [comment]
I think we can handle following data with this library

```json
{
    "type": "articles",
    "id": "tlgGJKIqxIo",
    "attributes": {
        "title": {
            "value": "This is the full title",
            "short": "Title in short"
        },
        ...
    }
}
```

And the Java code:

```java
public class TitleObject {
    String value;
    String short;
}
```

The `Article` class like:

```java
@JsonApi(type = "articles")
public class Article {
    TitleObject title;
    // ...
}
```

You can use customized adapter for `TitleObject` as is described by [moshi](https://github.com/square/moshi#custom-type-adapters)

**Comment by antonicg** [comment]
Okay thanks!
