### ISSUE TITLE
Run onFailure in Signed apk

### ISSUE THREAD

**Issue by mirmousaviii** [kamikat/moshi-jsonapi#53]
I used moshi-jsonapi and I have error in build signed apk (release mode), I used `dontwarn` in `proguard-rules.pro` for pass the build signed apk, But my application in signed mode every time run onFailure from Callback.
Throwable message:
`platform java.util.LinkedHashMap<java.lang.String,a.a.a.j> annotated [] requires explicit JsonAdapter to be registered`
I never have used LinkedHashMap, But when use moshi-jsonapi I have error in build.
**proguard-rules.pro:**
```
-dontwarn okio.**
-keep class okio.** { *; }

-dontwarn retrofit2.**
-dontwarn org.codehaus.mojo.**
-dontnote retrofit2.Platform
-dontnote retrofit2.Platform$IOS$MainThreadExecutor
-dontwarn retrofit2.Platform$Java8

-keep class retrofit2.** { *; }

-keepattributes Exceptions
-keepattributes Signature
-keepattributes RuntimeVisibleAnnotations
-keepattributes RuntimeInvisibleAnnotations
-keepattributes RuntimeVisibleParameterAnnotations
-keepattributes RuntimeInvisibleParameterAnnotations

-keepattributes EnclosingMethod
-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
-keepclasseswithmembers interface * {
    @retrofit2.* <methods>;
}
```

**Comment by kamikat** [comment]
Here's the minimal proguard rule I forgot adding to the documentation.

```
-keepattributes Signature
-keepclassmembers public abstract class moe.banana.jsonapi2.** {
   *;
}
```

**Comment by kamikat** [comment]
Investigated into my project using moshi-jsonapi. Seems that the project is obfuscated completely and everything works just ok... 

<img width="653" alt="screen shot 2017-03-03 at 12 42 07 pm" src="https://cloud.githubusercontent.com/assets/1108801/23538547/f9aa23c8-000e-11e7-91f9-f15fba4c599f.png">

With the library obfuscated as well... (actually, I have no idea about why it's obfuscated after I added these proguard rules)

![image](https://cloud.githubusercontent.com/assets/1108801/23538559/0b26fd9c-000f-11e7-926c-1e5dd6f63de7.png)

**Comment by kamikat** [comment]
BTW, the message

```
platform java.util.LinkedHashMap<java.lang.String,a.a.a.j> annotated [] requires explicit JsonAdapter to be registered
``` 

is to say that moshi is trying to deserialize someclass that have a field type of `a.a.a.j` but moshi could not find an adapter for that type. In most cases, it's a case of Enum that you've ever defined a JsonAdapter for. And maybe you need these proguard rules for moshi if you've defined a custom JsonAdapter:

```
-keepclassmembers class ** {
    @com.squareup.moshi.FromJson *;
    @com.squareup.moshi.ToJson *;
}
```

**Comment by mirmousaviii** [comment]
I use this code in proguard and resolved.
```
-keepclassmembers public abstract class moe.banana.jsonapi2.** {
   *;
}
```
Thank you

**Comment by kamikat** [comment]
But I have no idea why it works 😥😥😥 

Anyway, I'll add that to README, thanks.
