### ISSUE TITLE
Failed to resolve: moe.banana:moshi-jsonapi:3.2.1

### ISSUE THREAD

**Issue by skyred** [kamikat/moshi-jsonapi#56]
It's really weird that I can easily add moshi or retrofit, but I cannot add this dependency.

My app/build.gradle looks like:
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:support-v4:25.2.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.moshi:moshi:1.4.0'
    compile 'moe.banana:moshi-jsonapi:3.2.1'
    testCompile 'junit:junit:4.12'
}
```

and also have 

````
allprojects {
    repositories {
        jcenter()
    }
}
````

The error I received is:
````
Error:(31, 13) Failed to resolve: moe.banana:moshi-jsonapi:3.2.1
<a href="openFile:/....../app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
````

I tried 3.2.0 version, it's same error.

I also looked up https://bintray.com/kamikat/maven/moshi-jsonapi, it seems the dependencies declaration is correct.

I am trying to find more gradle error log, but I haven't managed to do that yet. Any hint for where to debug will be appreciated.

**Comment by skyred** [comment]
Ah, ok, found the problem. Apparently, jcenter only has 3.0.6 as its latest version: https://jcenter.bintray.com/moe/banana/moshi-jsonapi/

**Comment by kamikat** [comment]
Thanks for reporting. It seems like an issue with jcenter because artifacts
have been uploaded to bintray successfully.
https://bintray.com/kamikat/maven/moshi-jsonapi#files/moe/banana/moshi-jsonapi/3.2.1

I will reach them for help as soon as I can.
Jingsheng Wang <notifications@github.com>于2017年3月28日 周二18:49写道：

**Comment by skyred** [comment]
I forwarded this issue to bintray, and hope they can point us to the next step to fix it. https://twitter.com/skyredwang/status/846682431943958528

**Comment by kamikat** [comment]
I checked the repository again and just found the linkage to jcenter is missing. I've sent another package request to jcenter and waiting for a reply.

**Comment by kamikat** [comment]
The package is now added back to jcenter. https://jcenter.bintray.com/moe/banana/moshi-jsonapi/

**Comment by chiponn** [comment]
Hi, 

We have reviewed and resolved the issue you experienced. 
The root cause for this was a sync issue on our end.

We hope that this addresses your enquiry. 

Best Regards, 
Yonatan Brand
JFrog Support
