### ISSUE TITLE
Equals contract for data classes

### ISSUE THREAD

**Issue by p-fischer** [kamikat/moshi-jsonapi#58]
I want to write a valid equals method for my class extending from Resource taking into account its attributes.
The issue is that its superclass ResourceIdentifier already overwrites `equals()`.

One of the requirements for equals is symmetry. This is where I fail. Let's say my concrete instance is c an instance of ResourceIdentifier is s. If the both have equal type and id then `s.equals(c) == true`, however `c.equals(s) == false`.

There is a good read on that issue:
http://www.artima.com/lejava/articles/equality.html

I see three options:
1. I realize I do not need an extra equals method. (That would imply I do not consider the attributes of my concrete class to contribute to its state.)
2. ResourceIdentifier does not override equals at all (I have no idea if it is required.)
3. Using the `canEquals` approach as mentioned in the article to solve the problem.

**Comment by kamikat** [comment]
I've just released the patch to 3.2.2 🍻

**Comment by p-fischer** [comment]
There might be a misunderstanding. I want to have my own data class extending from Resource. In that data class I want to implement equals and hashcode in a way the equals contract is satisfied.
That is impossible right now since ResourceIdentifier, which is a transitive superclass, already implements equals / hashcode. Since my data class introduces new attributes, thus extends the classes state, I cannot implement equals in a way the symmetry requirement can be satisfied.

I know that's quite subtle, but [this testing library](https://github.com/jqno/equalsverifier) pointed me towards it.

**Comment by kamikat** [comment]
There you can override `equals` and `hashCode` function and use your own implementation.

**Comment by p-fischer** [comment]
That's what I did. Still the symmetry of the `equals` contract is not satisfied when I compare an instance of my own data class and an instance of `ResourceIdentifier`. See my first comment.

I just wanted to point that out. But you can consider it low prio ;)

**Comment by kamikat** [comment]
Umm... do you mean to make `a.equals(b) == true` as long as `a` and `b` are both instance of `ResourceIdentifier`?

**Comment by p-fischer** [comment]
I'd suggest the `canEqual` approach from my link above. That would cause `a.equals(b) == false` and `b.equals(a) == false` if a is a superclass of b.

**Comment by kamikat** [comment]
I read the article again. Generally, the [newly implemented](https://github.com/kamikat/moshi-jsonapi/commit/ce40acd37123874c87bd175e5215ad85c12dcdab#diff-3c92fa71e54372153219a94114e15474) `ResourceIdentifier` conforms to equality contract described there.
