### ISSUE TITLE
Has legacy Android dependency been moved?

### ISSUE THREAD

**Issue by es0329** [kamikat/moshi-jsonapi#59]
We need to publish a build of our app that uses _moe.banana.jsonapi:moshi-jsonapi-android:1.0.15_.
However, after working fine for months, Gradle is now unable to resolve this dependency.

![screen shot 2017-04-14 at 11 36 02 am](https://cloud.githubusercontent.com/assets/819901/25047762/ab376656-2106-11e7-9296-7fe2a7e3e56f.png)

This is a hotfix release. Our project's develop branch has been migrated up to _moshi-jsonapi:3.0.6_.

**Comment by kamikat** [comment]
Maybe there's something wrong with bintray. Pick up the version from jitpack.io may help.
