### ISSUE TITLE
gradle error app:_debugAnnotationProcessor

### ISSUE THREAD

**Issue by mikepschneider** [kamikat/moshi-jsonapi#60]
When I include this in build.grade:

    compile 'moe.banana:moshi-jsonapi:master-3.2.2'

I get this error:

Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.

Any way around this?

**Comment by kamikat** [comment]
Hmm... can you reproduce the error after removing the dependency to this library? I have no idea how this happens and not sure if version `master-3.2.2` is available from the repository (JitPack or Bintray).

You can also try to invalidate gradle build script cache to see if there's a problem with gradle.
