### ISSUE TITLE
Resource id as Object

### ISSUE THREAD

**Issue by yaroslavsudnik** [kamikat/moshi-jsonapi#61]
Our POST-request API requires this id format:
```
{
  "data": {
    "id": {
      "only": "organization"
    },
    "type": "users",
    "attributes": {
      ...
    }
  }
}
```
How can i achieve this?
Thanks

**Comment by kamikat** [comment]
Sorry, but the `id` and `type` must be string according to the specification <http://jsonapi.org/format/#document-resource-object-identification>
