### ISSUE TITLE
ProGuard issue

### ISSUE THREAD

**Issue by Sbf** [kamikat/moshi-jsonapi#62]
I've been unable to fix the crash when proGuard is enabled.
It says,
java.lang.NoSuchFieldError: No static field SERIALIZATION_AND_DESERIALIZATION of type Lmoe/banana/jsonapi2/Policy; in class Lmoe/banana/jsonapi2/Policy; or its superclasses

I did add these rules, but not working for some reason.

-keepattributes Signature
-keepclassmembers public abstract class moe.banana.jsonapi2.** {
    *;
}

-keepclassmembers class ** {
    @com.squareup.moshi.FromJson *;
    @com.squareup.moshi.ToJson *;
}

Any help would be appreciated!

**Comment by kamikat** [comment]
Does it work with following rule?

```
-keepattributes Signature
-keep class moe.banana.jsonapi2.** {
    *;
}
```

**Comment by Sbf** [comment]
I thought I tried that, but it worked!
Thanks kamikat!
