### ISSUE TITLE
How to handle generic nested data

### ISSUE THREAD

**Issue by tylergets** [kamikat/moshi-jsonapi#63]
Say I have a resource,  in my example a "GraphObject". 

It looks like this
```
{
    "id": "1",
    "type": "graph-objects",
    "attributes": {
      "name": "FEV1 Over Time",
      "type": "line",
      "values": [
        {
          "id": 1,
          "x": 1.76,
          "y": "2017-05-06T14:15:56.423Z"
        }
      ],
      "labels": {
        "x": "FEV1",
        "y": "Time"
      }
    }
  }
```

The nested field "values" will change, right now it contains an id,x, and y value. It's possible for that values field to contain other data (Such as name and count, if it's a pie graph)

I have attempted some OOP magic, but I am getting cast exceptions because of the internal values model. Is there a way to handle this and parse values to a hash map?

Thanks!

**Comment by kamikat** [comment]
The easiest way is to define `values` as `List<Map<String, Object>>`. 

You can also implement custom JSON adapter for objects contained by values attribute which produces different type of value based on their value. <https://github.com/square/moshi#custom-type-adapters>

Or you can define `values` as `JsonBuffer` which stores the data stream temporarily. And decide the adapter being used to deserialize at runtime.
