### ISSUE TITLE
Merging two ArrayDocuments with "addAll" seems to not add "includes"

### ISSUE THREAD

**Issue by davidherer** [kamikat/moshi-jsonapi#64]
I have an infinite scroll view which loads paginated data. When I load the second page and want to add it to the first ArrayDocument (with firstArrayDocument.addAll(mySecondArrayDocument)), the side-loaded data seem to not be correctly added since the relationships for the second loading give me null values.
Any idea or tricks to resolve my problem?
Thanks a lot

**Comment by kamikat** [comment]
Umm... Maybe `includeAll(Collection<Resource>)` and `excludeAll(Collection<Resource>)`?

**Comment by kamikat** [comment]
Introduce new API in 3.3.0:

```java
ArrayDocument<...> document1, document2;
document1.addAll(document2);
document1.getIncluded().addAll(document2.getIncluded());
```
