### ISSUE TITLE
Kotlin classes with Json annotations

### ISSUE THREAD

**Issue by dumazy** [kamikat/moshi-jsonapi#69]
The adapters don't work when using Kotlin classes with `Json(name = "..")` annotations. This is because annotations in Java are not the same as annotations in Kotlin and the adapters find no Json annotation.

The moshi [readme](https://github.com/square/moshi#kotlin-support) states this:

> Kotlin classes work with Moshi out of the box, with the exception of annotations. If you need to annotate your Kotlin classes with an @Json annotation or otherwise, you will need to use the moshi-kotlin artifact, and set up Moshi to use its converter factory:

> val moshi = Moshi.Builder()
>     .add(KotlinJsonAdapterFactory())
>     .build()

But this causes the `DocumentAdapter` to choose `KotlinJsonAdapter` as `dataJsonAdapter` instead of a `ResourceAdapter`, so the serialization to a json output with attributes, relationships, etc doesn't work.

**Comment by kamikat** [comment]
How about changing the order of adapter factories?

**Comment by dumazy** [comment]
If I put the KotlinJsonAdapterFactory after the ResourceAdapterFactory, the Json annotations are ignored. I debugged the flow and saw that KotlinJsonAdapter wasn't called.
If I put the KotlinJsonAdapterFactory first, the ResourceAdapters are not called.

**Comment by kamikat** [comment]
Umm... Can you try the `master-SNAPSHOT` version of the library to see if the new interface `ResourceAdapterFactory.Builder.setJsonNameMapping` works for your case?

By implementing `JsonNameMapping` in Kotlin, you can use functions provided by `kotlin.reflect` package to provide name information about the field/property.

**Comment by dumazy** [comment]
I've switched my models to Java classes already. I can test it with kotlin classes when I have time. I'll let you know if it works

**Comment by bricestacey** [comment]
I ran into this same problem. I was able to solve it with the following

```
    class MoshiJsonNameMapping : JsonNameMapping {
        override fun getJsonName(field: Field): String {
            val foo = field.kotlinProperty?.findAnnotation<Json>()
            return foo?.name ?: field.name
        }
    }
```

**Comment by Adonai** [comment]
Another solution:
Just annotate them with `@field:Json` instead of `@Json`

**Comment by premnirmal** [comment]
I'm experiencing the same issue. Using a json mapping didn't fix the issue for me. Any ideas? Thanks in advance.
