### ISSUE TITLE
Failed to resolve 'moe.banana:moshi-jsonapi:master-SNAPSHOT'

### ISSUE THREAD

**Issue by veerendra251** [kamikat/moshi-jsonapi#70]
Hi all,
  Till yesterday this library is working fine, but today when i am running my app, it is giving me 

 #  Failed to resolve 'moe.banana:moshi-jsonapi:master-SNAPSHOT'
 this error.

 Please help me in solving this issue.

Thanks

**Comment by kamikat** [comment]
Thank you for reporting the issue. There's a build error in the latest master commit (now fixed).

**Comment by ilhambagoes** [comment]
Hello @kamikat this issue happening again
