### ISSUE TITLE
Ignore includes

### ISSUE THREAD

**Issue by Pedroalexandrelopes** [kamikat/moshi-jsonapi#71]
The response from the server contains some included data that I don't need. I don't want to define these properties in my Resource object but I'm getting the error: "Unknown type of resource: ... ".
How should I ignore these cases and just serialize the properties defined in the Resource?
Thanks

**Comment by kamikat** [comment]
Refer <https://github.com/kamikat/moshi-jsonapi#fallback> to add the default type should solve your problem.

**Comment by Pedroalexandrelopes** [comment]
don't know how I missed that. Thank you, it's working now.
