### ISSUE TITLE
服务端新增了个类型，客户端没有就会解析错误吗？

### ISSUE THREAD

**Issue by gavinliu** [kamikat/moshi-jsonapi#72]
JsonAdapter.Factory jsonApiAdapterFactory = ResourceAdapterFactory.builder()
        .add(Comment.class)

解析未 add 的对象，就会解析不成功。

**Comment by gavinliu** [comment]
@JsonApi(type = "default")
class Unknown extends Resource {
    // nothing...
}

这个应该默认添加进去啊

**Comment by kamikat** [comment]
有道理，可以在 Builder 上加一个开关。
