### ISSUE TITLE
Filtering on moshi-jsonapi

### ISSUE THREAD

**Issue by dreamsbond** [kamikat/moshi-jsonapi#75]
Is it capable to apply filter on moshi-jsonapi?

**Comment by kamikat** [comment]
Umm... what's the 'filter'?

**Comment by dreamsbond** [comment]
@kamikat http://jsonapi.org/recommendations/#filtering

**Comment by kamikat** [comment]
Emmmmmm... it's the recommendation to a server route design and not JSONApi specification itself.
