### ISSUE TITLE
How to retrieve attributes from casting ResourceIdentifier to Resource of included?

### ISSUE THREAD

**Issue by dreamsbond** [kamikat/moshi-jsonapi#77]
No idea how to get there out.
Could you help?

**Comment by dreamsbond** [comment]
seems like i got the trick now.
```java
model.getRelationship(model.getDocument())
```

but this is based on included scenario.
would like to know more about resolving promise.

if i does not specify "include=relationship-a,relationship-b"
how does mosh-jsonapi work on resolving promise?


thanks

**Comment by kamikat** [comment]
What's a "promise"?

**Comment by dreamsbond** [comment]
The Promise object represents the eventual completion (or failure) of an asynchronous operation, and its resulting value.

**Comment by kamikat** [comment]
The library only handles object mappings in serialization/deserialization of JSON API objects for simplicity. So it does nothing with interacting with the server.

A general advice to this is to create a request to server retrieving all related resource objects and resolve the linkage with the context from that request.

**Comment by dreamsbond** [comment]
thanks.
yeah. i think having parsing "included" did the job.
