### ISSUE TITLE
Fails to deserialize hasMany relationship when empty

### ISSUE THREAD

**Issue by Bartheleway** [kamikat/moshi-jsonapi#80]
Hi, first thanks for your work.

I'm having some trouble with a hasMany relationship which actually has no records.

I have a JSON like that :
```json
{
  "data": [
    {
      "type": "articles",
      "id": "1",
      "attributes": {
        "title": "My Title",
      },
      "relationships": {
        "comments": {
          "data": null
        }
      }
    }
  ],
}
```

My model is like that
```java
@JsonApi(type = "article")
public class Article extends UpdatableResource {
  public String title;
  public HasMany<Comment> comments;
}
```

I'm getting this error :
`com.squareup.moshi.JsonDataException: Expected BEGIN_ARRAY but was NULL at path $.data[0].relationships.comments.data`

I'm using [this converter for retrofit](https://gist.github.com/kamikat/baa7d086f932b0dc4fc3f9f02e37a485)

**Comment by kamikat** [comment]
Released by 3.4.0 :tada:
