### ISSUE TITLE
How can I parse Metadata.

### ISSUE THREAD

**Issue by afinas-wii** [kamikat/moshi-jsonapi#90]
I am trying to parse metadata from a JosnApi for accessing fields inside `"meta":{...}`. What I'm getting is a JsonBuffer and I don't know how to parse data with this.

Thank you.

**Comment by kamikat** [comment]
You can parse meta attribute by implementing a `JsonAdapter` as is mentioned [here](https://github.com/kamikat/moshi-jsonapi#metalinksjsonapi-properties). And use `JsonBuffer.get(JsonAdapter)` for deserialization and `JsonBuffer.create(JsonAdapter, Object)` for serialization.

**Comment by afinas-wii** [comment]
Thanks for your response.
But I'm still facing the issue, This is my meta object, And how can I parse this.

```
"meta": {
"totalPages": 11,
"nextPage": 2,
"pageSize": 10
}
```

**Comment by kamikat** [comment]
Create a new class for your metadata and create a `JsonAdapter` from it as which is demonstrated by the [moshi example](https://github.com/square/moshi#moshi).
