### ISSUE TITLE
Double value should keep decimal portion when calling fromJsonValue on JsonAdapter<Document>

### ISSUE THREAD

**Issue by jasonbekolay** [kamikat/moshi-jsonapi#97]
Failing test is in this PR: https://github.com/kamikat/moshi-jsonapi/pull/96

Thank you for all your work on moshi-jsonapi!

**Comment by kamikat** [comment]
Merged :tada:

**Comment by jasonbekolay** [comment]
@kamikat Can you release a new version with this fix? Thanks again for reviewing and merging my PR!
